// WARNING: This file has been automatically generated by Full Inspector, as part of the serializer
//          selection wizard. It will be overwritten if you change your selected serializers.

using System;

namespace FullInspector.Internal {
    public class fiLoadedSerializers : fiILoadedSerializers {
        public Type DefaultSerializerProvider {
           get { return typeof(FullInspector.Serializers.FullSerializer.FullSerializerMetadata); }
        }

        public Type[] AllLoadedSerializerProviders {
           get {
               return new Type[] {
                    typeof(FullInspector.Serializers.FullSerializer.FullSerializerMetadata),
                    typeof(FullInspector.Serializers.JsonNet.JsonNetMetadata)
               };
           }
        }
    }
}
