// WARNING: This file has been automatically generated by Full Inspector, as part of the serializer
//          selection wizard. It will be overwritten if you change your selected serializers.

namespace FullInspector {
    public abstract class SharedInstance<T> : SharedInstance<T, FullInspector.FullSerializerSerializer> {}
}
