var class_full_inspector_1_1_samples_1_1_proto_buf_net_1_1_sample_proto_unity_types =
[
    [ "UnityTypesContainer", "struct_full_inspector_1_1_samples_1_1_proto_buf_net_1_1_sample_proto_unity_types_1_1_unity_types_container.html", "struct_full_inspector_1_1_samples_1_1_proto_buf_net_1_1_sample_proto_unity_types_1_1_unity_types_container" ],
    [ "UnityTypes", "class_full_inspector_1_1_samples_1_1_proto_buf_net_1_1_sample_proto_unity_types.html#a397cc9e4415bb251e68a96ca496f48cd", null ]
];