var namespace_full_inspector_1_1_serializers_1_1_full_serializer =
[
    [ "FullSerializerMetadata", "class_full_inspector_1_1_serializers_1_1_full_serializer_1_1_full_serializer_metadata.html", "class_full_inspector_1_1_serializers_1_1_full_serializer_1_1_full_serializer_metadata" ],
    [ "UnityObjectConverter", "class_full_inspector_1_1_serializers_1_1_full_serializer_1_1_unity_object_converter.html", "class_full_inspector_1_1_serializers_1_1_full_serializer_1_1_unity_object_converter" ]
];