var namespace_full_inspector_1_1_samples_1_1_other_1_1_delegates =
[
    [ "DelegateSampleBehavior", "class_full_inspector_1_1_samples_1_1_other_1_1_delegates_1_1_delegate_sample_behavior.html", "class_full_inspector_1_1_samples_1_1_other_1_1_delegates_1_1_delegate_sample_behavior" ]
];