var namespace_full_inspector_1_1_samples_1_1_other_1_1_disk_serialization =
[
    [ "DiskSerializedBehavior", "class_full_inspector_1_1_samples_1_1_other_1_1_disk_serialization_1_1_disk_serialized_behavior.html", "class_full_inspector_1_1_samples_1_1_other_1_1_disk_serialization_1_1_disk_serialized_behavior" ],
    [ "SerializedStruct", "struct_full_inspector_1_1_samples_1_1_other_1_1_disk_serialization_1_1_serialized_struct.html", "struct_full_inspector_1_1_samples_1_1_other_1_1_disk_serialization_1_1_serialized_struct" ]
];